### ISSUE TITLE
tkinter not available on Python 3.11

### ISSUE THREAD

**Issue by hendersj** [taabata/Comfy_Syrian_Falcon_Nodes#3]
```
Traceback (most recent call last):
  File "/<path>/ComfyUI/nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/<path>/ComfyUI/custom_nodes/SyrianFalconNodes.py", line 1, in <module>
    from tkinter import Y
ModuleNotFoundError: No module named 'tkinter'

Cannot import /<path>/ComfyUI/custom_nodes/SyrianFalconNodes.py module for custom nodes: No module named 'tkinter'
```

Trying to install it with pip results in it not being found.   Commenting out the import line for it will let it load, but the fonts aren't listed even though they are in the directories the script looks for them in.

Running on openSUSE Tumbleweed, using venv.

**Comment by hendersj** [comment]
Figured out that it's the 'tk' module that needs to be installed.  That probably needs to be set up in the installation, but fonts still are not found on my system, even though they're where they are expected to be.

**Comment by hendersj** [comment]
Opening a separate ticket on the font files not being found.
